export type DashboardHome = {
  user_id: string;
  display_name: string | null;
  greeting_text: string | null;
  insight_text: string | null;
  unique_items: number | null;
  total_pops: number | null;
  total_collection_value: number | null;
  total_paid: number | null;
  gain_loss: number | null;
  gain_loss_percent: number | null;
  average_paid_per_pop: number | null;
  average_value_per_pop: number | null;
  wishlist_count: number | null;
  pops_added_this_month: number | null;
  baseline_snapshot_date: string | null;
  baseline_collection_value: number | null;
  monthly_value_change: number | null;
  monthly_value_change_percent: number | null;
  generated_date: string | null;
};

export type PopCatalog = {
  id: string;
  created_at?: string | null;
  upc: string | null;
  pop_name: string | null;
  character: string | null;
  franchise: string | null;
  number: string | null;
  variant: string | null;
  exclusivity: string | null;
  pop_type: string | null;
  pop_style: string | null;
  set_name: string | null;
  image_url: string | null;
  vault_status: string | null;
  release_date: string | null;
  estimated_value: number | null;
  display_description: string | null;
  limited_edition: boolean | null;
  limited_count: number | null;
  edition_notes: string | null;
  api_last_updated?: string | null;
  parse_confidence?: number | null;
  parse_reason_codes?: string[] | null;
  needs_review?: boolean | null;
};

export type CollectionItem = {
  collection_item_id: string;
  user_id: string;
  pop_catalog_id: string;
  quantity: number | null;
  condition: string | null;
  owned_variant: string | null;
  purchase_price: number | null;
  current_value: number | null;
  notes: string | null;
  for_trade: boolean | null;
  for_sale: boolean | null;
  listing_status?: "keeping" | "for_sale" | "for_trade" | "sale_or_trade" | "sold" | string | null;
  asking_price?: number | null;
  minimum_price?: number | null;
  listing_platform?: string | null;
  listed_at?: string | null;
  trade_notes?: string | null;
  acquired_date?: string | null;
  created_at?: string | null;
  upc: string | null;
  pop_name: string | null;
  character: string | null;
  franchise: string | null;
  number: string | null;
  variant: string | null;
  exclusivity: string | null;
  pop_type: string | null;
  pop_style: string | null;
  set_name: string | null;
  image_url: string | null;
  vault_status: string | null;
  release_date: string | null;
  estimated_value: number | null;
  value_each: number | null;
  total_value: number | null;
  total_cost: number | null;
  gain_loss: number | null;
  display_variant: string | null;
  display_description: string | null;
  limited_edition: boolean | null;
  limited_count: number | null;
  edition_notes: string | null;
  signed: boolean | null;
  signed_by: string | null;
  signature_authentication: string | null;
  signature_cert_number: string | null;
  signature_location: string | null;
  signature_personalized: boolean | null;
  signature_notes: string | null;
  signed_value_boost_percent: number | null;
  signed_estimated_value_low?: number | null;
  signed_estimated_value_median?: number | null;
  signed_estimated_value_high?: number | null;
  signed_value_confidence?: "low" | "medium" | "high" | string | null;
  signed_value_source?: string | null;
  signed_value_last_checked?: string | null;
};

export type PopSale = {
  id: string;
  user_id: string;
  collection_item_id: string | null;
  pop_catalog_id: string | null;
  sold_at: string | null;
  sale_price: number | null;
  platform: string | null;
  platform_fees: number | null;
  shipping_charged: number | null;
  shipping_cost: number | null;
  purchase_price: number | null;
  estimated_value_at_sale: number | null;
  pop_name: string | null;
  franchise: string | null;
  set_name: string | null;
  number: string | null;
  variant: string | null;
  image_url: string | null;
  notes: string | null;
  created_at: string | null;
  updated_at: string | null;
};

export type SharedShelf = {
  id: string;
  name: string;
  description: string | null;
  invite_code: string;
  created_by: string;
  created_at: string;
  updated_at: string;
  member_names: string | null;
  member_count: number | null;
};

export type SharedShelfMember = {
  id: string;
  shelf_id: string;
  user_id: string;
  role: "owner" | "member" | string;
  created_at: string;
  display_name: string | null;
  username: string | null;
};

export type SharedShelfCollectionItem = CollectionItem & {
  shelf_id: string;
  shelf_name: string;
  invite_code: string;
  owner_user_id: string;
  owner_display_name: string;
  created_at: string | null;
  signed_count?: number | null;
  signature_authentication?: string | null;
};

export type SharedShelfGroupedItem = {
  shelf_id: string;
  shelf_name: string;
  invite_code: string;
  pop_catalog_id: string;
  upc: string | null;
  pop_name: string | null;
  character: string | null;
  franchise: string | null;
  number: string | null;
  variant: string | null;
  exclusivity: string | null;
  pop_type: string | null;
  pop_style: string | null;
  set_name: string | null;
  image_url: string | null;
  vault_status: string | null;
  release_date: string | null;
  estimated_value: number | null;
  display_description: string | null;
  limited_edition: boolean | null;
  limited_count: number | null;
  edition_notes: string | null;
  total_quantity: number | null;
  owner_count: number | null;
  owner_names: string | null;
  variants_owned: string | null;
  value_each: number | null;
  total_value: number | null;
  total_cost: number | null;
  gain_loss: number | null;
  newest_added_at: string | null;
  signed_count: number | null;
  signature_authentication: string | null;
};

export type Profile = {
  id: string;
  username: string | null;
  display_name: string | null;
  avatar_url: string | null;
  bio: string | null;
  is_public: boolean | null;
  collector_mode?: "casual" | "avid" | "reseller" | null;
};

export type PublicWishlistItem = {
  id: string;
  user_id: string;
  pop_catalog_id: string;
  priority: string | null;
  notes: string | null;
  created_at: string | null;
  owner_display_name: string | null;
  owner_username: string | null;
  owner_avatar_url: string | null;
  upc: string | null;
  pop_name: string | null;
  character: string | null;
  franchise: string | null;
  number: string | null;
  variant: string | null;
  exclusivity: string | null;
  pop_type: string | null;
  pop_style: string | null;
  set_name: string | null;
  image_url: string | null;
  vault_status: string | null;
  release_date: string | null;
  estimated_value: number | null;
  display_description: string | null;
  limited_edition: boolean | null;
  limited_count: number | null;
  edition_notes: string | null;
};

export type LookupResponse = {
  found: boolean;
  source?: string;
  message?: string;
  error?: string;
  pop?: PopCatalog;
};

export type AdminUser = {
  user_id: string;
  created_at: string | null;
  notes: string | null;
};

export type CatalogIssueReport = {
  id: string;
  reporter_user_id: string;
  pop_catalog_id: string | null;
  collection_item_id: string | null;
  issue_type: string;
  notes: string | null;
  status: "open" | "resolved" | "ignored" | string;
  admin_notes: string | null;
  resolved_by: string | null;
  resolved_at: string | null;
  created_at: string | null;
  updated_at: string | null;
  reporter_display_name?: string | null;
  reporter_username?: string | null;
  upc?: string | null;
  pop_name?: string | null;
  franchise?: string | null;
  number?: string | null;
  variant?: string | null;
  set_name?: string | null;
  image_url?: string | null;
  estimated_value?: number | null;
};

export type AdminAuditEvent = {
  id: string;
  actor_user_id: string | null;
  action: string;
  table_name: string;
  row_id: string | null;
  related_report_id: string | null;
  before_data: Record<string, unknown> | null;
  after_data: Record<string, unknown> | null;
  changed_fields: string[] | null;
  created_at: string | null;
};

export type CatalogParserOverride = {
  id: string;
  upc: string;
  pop_catalog_id: string | null;
  override_data: Record<string, unknown>;
  learned_from_audit_event_id: string | null;
  created_by: string | null;
  updated_by: string | null;
  created_at: string | null;
  updated_at: string | null;
  is_active: boolean;
  notes: string | null;
  pop_name?: string | null;
  character?: string | null;
  franchise?: string | null;
  number?: string | null;
  variant?: string | null;
  set_name?: string | null;
  image_url?: string | null;
};
