-- Star Wars reviewed-set move parser overrides, staged 2026-07-09.
-- Purpose:
-- - Persist the July 9 reviewed movie-set placements so generic Star Wars refreshes
--   do not drift rows back out of the reviewed canonical set names.
-- - Match the live public.catalog_parser_overrides table shape used in production:
--   override data is stored in override_data JSONB.

insert into public.catalog_parser_overrides (upc, pop_catalog_id, override_data, notes, is_active)
values
  ('830395023908', (select id from public.pop_catalog where upc = '830395023908' limit 1), jsonb_build_object('pop_name','Darth Maul','character','Darth Maul','franchise','Star Wars','set_name','Star Wars: The Phantom Menace','number','9','pop_type','Pop! Star Wars','pop_style','Standard','description','Darth Maul belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #9.','display_description','Darth Maul belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #9.','parse_confidence',0.98,'needs_review',false), 'Reviewed Phantom Menace move.', true),
  ('889698376662', (select id from public.pop_catalog where upc = '889698376662' limit 1), jsonb_build_object('pop_name','Watto','character','Watto','franchise','Star Wars','set_name','Star Wars: The Phantom Menace','number','298','exclusivity','Star Wars Celebration','pop_type','Pop! Star Wars','pop_style','Standard','description','Watto belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #298. This catalog entry tracks the Star Wars Celebration exclusive.','display_description','Watto belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #298. This catalog entry tracks the Star Wars Celebration exclusive.','parse_confidence',0.98,'needs_review',false), 'Reviewed Phantom Menace move.', true),
  ('889698406772', (select id from public.pop_catalog where upc = '889698406772' limit 1), jsonb_build_object('pop_name','Aurra Sing','character','Aurra Sing','franchise','Star Wars','set_name','Star Wars: The Phantom Menace','number','303','exclusivity','Smuggler''s Bounty','pop_type','Pop! Star Wars','pop_style','Standard','description','Aurra Sing belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #303. This catalog entry tracks the Smuggler''s Bounty exclusive.','display_description','Aurra Sing belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #303. This catalog entry tracks the Smuggler''s Bounty exclusive.','parse_confidence',0.98,'needs_review',false), 'Reviewed Phantom Menace move.', true),
  ('889698760188', (select id from public.pop_catalog where upc = '889698760188' limit 1), jsonb_build_object('pop_name','Obi-Wan Kenobi (Padawan)','character','Obi-Wan Kenobi','franchise','Star Wars','set_name','Star Wars: The Phantom Menace','number','699','variant','Padawan','pop_type','Pop! Star Wars','pop_style','Standard','description','Obi-Wan Kenobi (Padawan) belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #699.','display_description','Obi-Wan Kenobi (Padawan) belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #699.','parse_confidence',0.98,'needs_review',false), 'Reviewed Phantom Menace move.', true),
  ('889698760218', (select id from public.pop_catalog where upc = '889698760218' limit 1), jsonb_build_object('pop_name','Watto','character','Watto','franchise','Star Wars','set_name','Star Wars: The Phantom Menace','number','702','pop_type','Pop! Star Wars','pop_style','Standard','description','Watto belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #702.','display_description','Watto belongs to the Star Wars: The Phantom Menace Pop! Star Wars line as #702.','parse_confidence',0.98,'needs_review',false), 'Reviewed Phantom Menace move.', true),
  ('849803065744', (select id from public.pop_catalog where upc = '849803065744' limit 1), jsonb_build_object('pop_name','AT-AT Driver','character','AT-AT Driver','franchise','Star Wars','set_name','Star Wars: The Empire Strikes Back','number','92','exclusivity','Walgreens','pop_type','Pop! Star Wars','pop_style','Standard','description','AT-AT Driver belongs to the Star Wars: The Empire Strikes Back Pop! Star Wars line as #92. This catalog entry tracks the Walgreens exclusive.','display_description','AT-AT Driver belongs to the Star Wars: The Empire Strikes Back Pop! Star Wars line as #92. This catalog entry tracks the Walgreens exclusive.','parse_confidence',0.98,'needs_review',false), 'Reviewed Empire Strikes Back move.', true),
  ('889698101059', (select id from public.pop_catalog where upc = '889698101059' limit 1), jsonb_build_object('pop_name','Dagobah Yoda','character','Yoda','franchise','Star Wars','set_name','Star Wars: The Empire Strikes Back','number','124','pop_type','Pop! Star Wars','pop_style','Standard','description','Dagobah Yoda belongs to the Star Wars: The Empire Strikes Back Pop! Star Wars line as #124.','display_description','Dagobah Yoda belongs to the Star Wars: The Empire Strikes Back Pop! Star Wars line as #124.','parse_confidence',0.98,'needs_review',false), 'Reviewed Empire Strikes Back move.', true),
  ('889698561051', (select id from public.pop_catalog where upc = '889698561051' limit 1), jsonb_build_object('pop_name','Bounty Hunters Collection: Dengar','character','Dengar','franchise','Star Wars','set_name','Star Wars: The Empire Strikes Back','number','440','exclusivity','GameStop','pop_type','Pop! Star Wars','pop_style','Standard','description','Bounty Hunters Collection: Dengar belongs to the Star Wars: The Empire Strikes Back Pop! Star Wars line as #440. This catalog entry tracks the GameStop exclusive.','display_description','Bounty Hunters Collection: Dengar belongs to the Star Wars: The Empire Strikes Back Pop! Star Wars line as #440. This catalog entry tracks the GameStop exclusive.','parse_confidence',0.98,'needs_review',false), 'Reviewed Empire Strikes Back move.', true),
  ('849803057794', (select id from public.pop_catalog where upc = '849803057794' limit 1), jsonb_build_object('pop_name','Nalan Cheel','character','Nalan Cheel','franchise','Star Wars','set_name','Star Wars: A New Hope','number','52','pop_type','Pop! Star Wars','pop_style','Standard','description','Nalan Cheel belongs to the Star Wars: A New Hope Pop! Star Wars line as #52.','display_description','Nalan Cheel belongs to the Star Wars: A New Hope Pop! Star Wars line as #52.','parse_confidence',0.98,'needs_review',false), 'Reviewed A New Hope move.', true),
  ('889698430166', (select id from public.pop_catalog where upc = '889698430166' limit 1), jsonb_build_object('pop_name','Luke Skywalker (Bespin)','character','Luke Skywalker','franchise','Star Wars','set_name','Star Wars: A New Hope','number','93','variant','Metallic','exclusivity','Walmart','pop_type','Pop! Star Wars','pop_style','Standard','description','Luke Skywalker (Bespin) belongs to the Star Wars: A New Hope Pop! Star Wars line as #93. This catalog entry tracks the Metallic Walmart exclusive.','display_description','Luke Skywalker (Bespin) belongs to the Star Wars: A New Hope Pop! Star Wars line as #93. This catalog entry tracks the Metallic Walmart exclusive.','parse_confidence',0.98,'needs_review',false), 'Reviewed A New Hope move.', true),
  ('889698129084', (select id from public.pop_catalog where upc = '889698129084' limit 1), jsonb_build_object('pop_name','Muftak','character','Muftak','franchise','Star Wars','set_name','Star Wars: A New Hope','number','173','exclusivity','Spring Convention','pop_type','Pop! Star Wars','pop_style','Standard','description','Muftak belongs to the Star Wars: A New Hope Pop! Star Wars line as #173. This catalog entry tracks the Spring Convention exclusive.','display_description','Muftak belongs to the Star Wars: A New Hope Pop! Star Wars line as #173. This catalog entry tracks the Spring Convention exclusive.','parse_confidence',0.98,'needs_review',false), 'Reviewed A New Hope move.', true),
  ('889698390835', (select id from public.pop_catalog where upc = '889698390835' limit 1), jsonb_build_object('pop_name','Princess Leia (Gold Chrome)','character','Princess Leia','franchise','Star Wars','set_name','Star Wars: A New Hope','number','295','variant','Gold Chrome','pop_type','Pop! Star Wars','pop_style','Standard','description','Princess Leia (Gold Chrome) belongs to the Star Wars: A New Hope Pop! Star Wars line as #295.','display_description','Princess Leia (Gold Chrome) belongs to the Star Wars: A New Hope Pop! Star Wars line as #295.','parse_confidence',0.98,'needs_review',false), 'Reviewed A New Hope move.', true),
  ('889698475983', (select id from public.pop_catalog where upc = '889698475983' limit 1), jsonb_build_object('pop_name','Jawa','character','Jawa','franchise','Star Wars','set_name','Star Wars: A New Hope','number','371','pop_type','Pop! Star Wars','pop_style','Standard','description','Jawa belongs to the Star Wars: A New Hope Pop! Star Wars line as #371.','display_description','Jawa belongs to the Star Wars: A New Hope Pop! Star Wars line as #371.','parse_confidence',0.98,'needs_review',false), 'Reviewed A New Hope move.', true),
  ('849803057091', (select id from public.pop_catalog where upc = '849803057091' limit 1), jsonb_build_object('pop_name','Princess Leia (Boushh)','character','Princess Leia','franchise','Star Wars','set_name','Star Wars: Return of the Jedi','number','50','pop_type','Pop! Star Wars','pop_style','Standard','description','Princess Leia (Boushh) belongs to the Star Wars: Return of the Jedi Pop! Star Wars line as #50.','display_description','Princess Leia (Boushh) belongs to the Star Wars: Return of the Jedi Pop! Star Wars line as #50.','parse_confidence',0.98,'needs_review',false), 'Reviewed Return of the Jedi move.', true),
  ('889698707480', (select id from public.pop_catalog where upc = '889698707480' limit 1), jsonb_build_object('pop_name','Princess Leia (Boushh)','character','Princess Leia','franchise','Star Wars','set_name','Star Wars: Return of the Jedi 40th Anniversary','number','606','variant','Boushh','pop_type','Pop! Star Wars','pop_style','Standard','description','Princess Leia (Boushh) belongs to the Star Wars: Return of the Jedi 40th Anniversary Pop! Star Wars line as #606.','display_description','Princess Leia (Boushh) belongs to the Star Wars: Return of the Jedi 40th Anniversary Pop! Star Wars line as #606.','parse_confidence',0.98,'needs_review',false), 'Reviewed Return of the Jedi 40th Anniversary move.', true)
on conflict (upc) do update
set
  pop_catalog_id = excluded.pop_catalog_id,
  override_data = excluded.override_data,
  notes = excluded.notes,
  is_active = excluded.is_active;

select
  upc,
  pop_catalog_id,
  override_data ->> 'set_name' as set_name,
  override_data ->> 'number' as number,
  override_data ->> 'variant' as variant,
  override_data ->> 'exclusivity' as exclusivity,
  override_data ->> 'needs_review' as needs_review,
  is_active,
  notes
from public.catalog_parser_overrides
where upc in (
  '830395023908','889698376662','889698406772','889698760188','889698760218',
  '849803065744','889698101059','889698561051',
  '849803057794','889698430166','889698129084','889698390835','889698475983',
  '849803057091','889698707480'
)
order by upc;
