export const GENERIC_SET_NAMES = new Set(["Star Wars", "DC", "Marvel", "Disney", "N/A"]);

export const BLOCKED_IMAGE_UPCS = new Set([
  "889698430210",
  "889698217842",
]);

export const SET_TOTAL_OVERRIDES: Record<string, number> = {
  "300 Movie": 6,
  "Aquaman and the Lost Kingdom": 13,
  "Aquaman And The Lost Kingdom": 13,
  "Ant-Man and the Wasp: Quantumania": 13,
  "Arrow": 13,
  "Black Clover": 35,
  "Black Lanterns": 1,
  "Black Panther": 31,
  "Black Panther: Wakanda Forever": 36,
  "Birds of Prey": 11,
  "Brandalised. Banksy": 2,
  "Brave": 1,
  "Bullet Train": 4,
  "Caddyshack": 11,
  "Captain America: The First Avenger": 3,
  "Cartoon Network": 8,
  "Chilly Willy": 4,
  "Cocaine Bear": 2,
  "Coco": 13,
  "Crash Bandicoot": 13,
  "Cuphead": 30,
  "Deadpool The Duck": 1,
  "Despicable Me 2": 10,
  "Dexter": 3,
  "Disney Archives": 8,
  "Disturbed": 1,
  "Dolly Parton": 6,
  "Duck Dodgers": 12,
  "Dumb And Dumber": 14,
  "Dumb and Dumber": 14,
  "Dumbo": 7,
  "Disneyland Resort 65th Anniversary": 20,
  "Echo": 2,
  "Elvis Presley": 18,
  "Evil Dead 40th Anniversary": 2,
  "Fantasia": 12,
  "Fantastik Plastik": 73,
  "Fantastic Beasts: The Crimes of Grindelwald": 40,
  "Finding Dory": 2,
  "Fortnite": 64,
  "Free Guy": 1,
  "Frozen": 26,
  "G.I. Joe": 25,
  "Grey's Anatomy": 4,
  "Guardians of the Galaxy Holiday Special": 5,
  "Gwen-Verse": 4,
  "Hall of Armor": 4,
  "Hellboy": 16,
  "Hercules": 8,
  "Hobbs And Shaw": 4,
  "House": 1,
  "I Am Groot": 26,
  "Indiana Jones": 28,
  "Indiana Jones and the Last Crusade": 3,
  "Ironheart": 2,
  "Infinity Warps": 15,
  "It's A Small World": 6,
  "Jingle All the Way": 5,
  "Jungle Cruise": 1,
  "Jurassic Park: 25th Anniversary": 7,
  "Jessica Jones": 2,
  "Krypto The Superdog": 1,
  "Married With Children": 6,
  "Make A Wish": 9,
  "Make-A-Wish": 9,
  "Mark Hamill": 2,
  "Marvel Street Art": 7,
  "Marvel Zombies": 34,
  "Mike Tyson": 1,
  "Monster At Work": 2,
  "Monsters, Inc": 18,
  "Monsters, Inc.": 18,
  "Nacho Libre": 2,
  "Onward": 7,
  "Pinky and the Brain": 1,
  "Poltergeist II: The Other Side": 1,
  "Preacher": 6,
  "Pirates Of The Caribbean Dead Men Tell No Tales": 5,
  "Psych": 1,
  "Robocop": 5,
  "Runaways": 6,
  "RUN-DMC": 10,
  "Saturday Night Live": 9,
  "Sherlock": 6,
  "She-Hulk: Attorney at Law": 10,
  "Justice League Comics": 7,
  "Shazam!": 7,
  "Shazam! Fury of the Gods": 10,
  "Shazam! Fury Of The Gods": 10,
  "Sleepy Hollow (1999)": 5,
  "Sleeping Beauty 65th Anniversary": 10,
  "Spider-Man 2": 10,
  "Spider-Man: Far From Home": 15,
  "Spider-Man: Into The Spider-Verse": 11,
  "Spider-Man: Maximum Venom": 9,
  "Spider-Man: Miles Morales": 16,
  "Spellbound": 1,
  "Stargate SG-1": 7,
  "Star Trek II: The Wrath of Khan": 2,
  "Star Trek The Next Generation": 5,
  "Star Trek Transporter": 3,
  "Ted Lasso": 23,
  "The Batman": 15,
  "The Flash (TV Series)": 21,
  "The Godfather: 50 Years": 3,
};

export const STAR_WARS_REFRESH_REGRESSION_OVERRIDES = {
  "889698818667": {
    raw_title: "Fear Gas Batman #532",
    clean_title: "Fear Gas Batman #532",
    pop_name: "Fear Gas Batman",
    character: "Batman",
    franchise: "DC",
    set_name: "Batman Begins",
    number: "532",
    variant: "Fear Gas",
    exclusivity: "Funko Shop",
    pop_type: "Pop! Heroes",
    pop_style: "Standard",
    vault_status: "Active",
    release_date: "2024-10-07",
    limited_edition: false,
    limited_count: null,
    edition_notes: "Funko Shop exclusive",
    description: "Fear Gas Batman belongs to the Batman Begins Pop! Heroes line as #532, Funko Shop exclusive.",
    display_description: "Fear Gas Batman belongs to the Batman Begins Pop! Heroes line as #532, Funko Shop exclusive. Released in 2024.",
    estimated_value: 26.49,
    parse_confidence: 0.98,
    needs_review: false,
    warnings: [],
  },
  "889698918008": {
    raw_title: "Padme Amidala in Lake Dress #812",
    clean_title: "Padme Amidala in Lake Dress #812",
    pop_name: "Padme Amidala",
    character: "Padme Amidala",
    franchise: "Star Wars",
    set_name: "Star Wars: Attack of the Clones",
    number: "812",
    variant: "Lake Dress",
    exclusivity: "Funko Shop",
    pop_type: "Pop! Star Wars",
    pop_style: "Standard",
    vault_status: "Active",
    release_date: "2025-10-21",
    limited_edition: false,
    limited_count: null,
    edition_notes: "Funko web exclusive",
    description: "Padme Amidala belongs to the Star Wars: Attack of the Clones Pop! Star Wars line as #812, Lake Dress variant, Funko Shop exclusive.",
    display_description: "Padme Amidala belongs to the Star Wars: Attack of the Clones Pop! Star Wars line as #812, Lake Dress variant, Funko Shop exclusive. Released in 2025.",
    estimated_value: 48.67,
    parse_confidence: 0.98,
    needs_review: false,
    warnings: [],
  },
  "889698585019": {
    raw_title: "Hawkgirl (Bombshells) (Breast Cancer Awareness) #223",
    clean_title: "Hawkgirl Bombshells Breast Cancer Awareness #223",
    pop_name: "Hawkgirl",
    character: "Hawkgirl",
    franchise: "DC",
    set_name: "DC Comics Bombshells",
    number: "223",
    variant: "Breast Cancer Awareness",
    exclusivity: "Target",
    pop_type: "Pop! Heroes",
    pop_style: "Standard",
    vault_status: "Vaulted",
    release_date: "2021-08-29",
    limited_edition: false,
    limited_count: null,
    edition_notes: "Target exclusive Breast Cancer Awareness edition",
    description: "Hawkgirl belongs to the DC Comics Bombshells Pop! Heroes line as #223, Breast Cancer Awareness Target exclusive.",
    display_description: "Hawkgirl belongs to the DC Comics Bombshells Pop! Heroes line as #223, Breast Cancer Awareness Target exclusive. Released in 2021.",
    estimated_value: 7.15,
    parse_confidence: 0.98,
    needs_review: false,
    warnings: [],
  },
  "889698608527": {
    raw_title: "Doctor Strange #4",
    clean_title: "Doctor Strange #4",
    pop_name: "Doctor Strange",
    character: "Doctor Strange",
    franchise: "Marvel",
    set_name: "Marvel Comics",
    number: "4",
    variant: null,
    exclusivity: "Target",
    pop_type: "Pop! Comic Covers",
    pop_style: "Comic Cover",
    vault_status: "Active",
    release_date: null,
    limited_edition: false,
    limited_count: null,
    edition_notes: "Target exclusive comic cover",
    description: "Doctor Strange belongs to the Marvel Comics Pop! Comic Covers line as #4, Target exclusive.",
    display_description: "Doctor Strange belongs to the Marvel Comics Pop! Comic Covers line as #4, Target exclusive.",
    estimated_value: 7.93,
    parse_confidence: 0.98,
    needs_review: false,
    warnings: [],
  },
  "889698546485": {
    raw_title: "Whit Merrifield (Home Uniform) #69",
    clean_title: "Whit Merrifield Home Uniform #69",
    pop_name: "Whit Merrifield",
    character: "Whit Merrifield",
    franchise: "MLB",
    set_name: "MLB: Kansas City Royals",
    set_total: 9,
    number: "69",
    variant: "Home Uniform",
    exclusivity: null,
    pop_type: "Pop! MLB",
    pop_style: "Standard",
    vault_status: "Vaulted",
    release_date: "2021-01-01",
    limited_edition: false,
    limited_count: null,
    edition_notes: null,
    description: "Whit Merrifield belongs to the MLB: Kansas City Royals Pop! MLB line as #69, Home Uniform variant.",
    display_description: "Whit Merrifield belongs to the MLB: Kansas City Royals Pop! MLB line as #69, Home Uniform variant. Released in 2021.",
    estimated_value: 12.36,
    parse_confidence: 0.98,
    needs_review: false,
    warnings: [],
  },
  "889698160162": {
    raw_title: "Ben Kenobi #99",
    clean_title: "Ben Kenobi #99",
    pop_name: "Ben Kenobi",
    character: "Ben Kenobi",
    franchise: "Star Wars",
    set_name: "Star Wars: A New Hope",
    number: "99",
    variant: null,
    exclusivity: "Smuggler's Bounty",
    pop_type: "Pop! Star Wars",
    pop_style: "Standard",
    vault_status: "Vaulted",
    release_date: "2016-01-01",
    limited_edition: false,
    limited_count: null,
    edition_notes: "Smuggler's Bounty exclusive",
    description: "Ben Kenobi belongs to the Star Wars: A New Hope Pop! Star Wars line as #99, Smuggler's Bounty exclusive.",
    display_description: "Ben Kenobi belongs to the Star Wars: A New Hope Pop! Star Wars line as #99, Smuggler's Bounty exclusive. Released in 2016.",
    estimated_value: 13.99,
    image_url: "https://vwlnlgqxjamkukssuajt.supabase.co/storage/v1/object/public/pop-images/manual/ben-kenobi-99-889698160162.jpg",
    parse_confidence: 0.98,
    needs_review: false,
    warnings: [],
  },
  "889698430180": {
    pop_name: "Yoda",
    character: "Yoda",
    franchise: "Star Wars",
    set_name: "Star Wars: The Empire Strikes Back",
    number: "124",
    variant: "Metallic Gold",
    exclusivity: "Walmart",
    pop_type: "Pop! Star Wars",
    pop_style: "Standard",
    description: "Yoda is a Star Wars: The Empire Strikes Back Pop! release #124, Walmart exclusive, metallic gold.",
    display_description: "Yoda is a Star Wars: The Empire Strikes Back Pop! release #124, Walmart exclusive, metallic gold.",
    parse_confidence: 0.98,
    needs_review: false,
    warnings: [],
  },
  "889698430203": {
    pop_name: "Darth Maul (Gold Metallic)",
    character: "Darth Maul",
    franchise: "Star Wars",
    set_name: "Star Wars: The Phantom Menace",
    number: "9",
    variant: "Metallic Gold",
    exclusivity: "Walmart",
    vault_status: "Vaulted",
    pop_type: "Pop! Star Wars",
    pop_style: "Standard",
    description: "Darth Maul (Gold Metallic) is a Star Wars: The Phantom Menace Pop! release #9, Walmart exclusive.",
    display_description: "Darth Maul (Gold Metallic) is a Star Wars: The Phantom Menace Pop! release #9, Walmart exclusive.",
    parse_confidence: 0.98,
    needs_review: false,
    warnings: [],
  },
  "849803087159": {
    pop_name: "Blue Senate Guard",
    character: "Blue Senate Guard",
    franchise: "Star Wars",
    set_name: "Star Wars: Attack of the Clones",
    number: "98",
    exclusivity: "Galactic Convention",
    pop_type: "Pop! Star Wars",
    pop_style: "Standard",
    description: "Blue Senate Guard is a Star Wars: Attack of the Clones Pop! release #98, Galactic Convention exclusive.",
    display_description: "Blue Senate Guard is a Star Wars: Attack of the Clones Pop! release #98, Galactic Convention exclusive.",
    parse_confidence: 0.98,
    needs_review: false,
    warnings: [],
  },
};

type CatalogRow = Record<string, any>;

export function getStaticCatalogOverride(upc: string): CatalogRow | null {
  return (STAR_WARS_REFRESH_REGRESSION_OVERRIDES as Record<string, CatalogRow>)[upc] ?? null;
}

type RefreshOptions = {
  forceRefresh: boolean;
  hasExclusivityOverride: boolean;
  exclusivityOverride?: string | null;
  imageBlocked: boolean;
  resolvedRefreshEstimatedValue: number | null;
};

function normalizeSetName(value: unknown): string {
  return String(value ?? "").replace(/\s+/g, " ").trim();
}

export function getSetTotalOverride(setName: unknown): number | null {
  const normalized = normalizeSetName(setName);
  return SET_TOTAL_OVERRIDES[normalized] ?? null;
}

export function shouldPromoteSpecificSet(existingSetName: unknown, parsedSetName: unknown): boolean {
  const existing = normalizeSetName(existingSetName);
  const parsed = normalizeSetName(parsedSetName);

  if (!parsed) return false;
  if (!existing) return true;
  return GENERIC_SET_NAMES.has(existing) && parsed !== existing;
}

export function mergeNeedsReview(existingNeedsReview: unknown, parsedNeedsReview: unknown): boolean {
  return Boolean(existingNeedsReview || parsedNeedsReview);
}

export function buildCatalogRefreshUpdate(
  existing: CatalogRow,
  newPop: CatalogRow,
  options: RefreshOptions,
): CatalogRow {
  const exclusivity = options.hasExclusivityOverride
    ? options.exclusivityOverride
    : (newPop.exclusivity || existing.exclusivity);

  if (options.forceRefresh) {
    return {
      pop_name: newPop.pop_name || existing.pop_name,
      character: newPop.character || existing.character,
      franchise: newPop.franchise || existing.franchise,
      number: newPop.number || existing.number,
      variant: newPop.variant || existing.variant,
      exclusivity,
      pop_type: newPop.pop_type || existing.pop_type,
      pop_style: newPop.pop_style || existing.pop_style,
      set_name: newPop.set_name || existing.set_name,
      set_total: existing.set_total ?? newPop.set_total,
      vault_status: newPop.vault_status || existing.vault_status,
      limited_edition: newPop.limited_edition || existing.limited_edition,
      limited_count: newPop.limited_count ?? existing.limited_count,
      edition_notes: newPop.edition_notes || existing.edition_notes,
      estimated_value: options.resolvedRefreshEstimatedValue,
      description: newPop.description || existing.description,
      display_description: newPop.display_description || existing.display_description,
      api_source: newPop.api_source || existing.api_source,
      api_last_updated: newPop.api_last_updated,
      raw_api_json: newPop.raw_api_json ?? existing.raw_api_json,
      image_url: options.imageBlocked ? null : existing.image_url,
      release_date: newPop.release_date || existing.release_date,
      raw_title: newPop.raw_title || existing.raw_title,
      clean_title: newPop.clean_title || existing.clean_title,
      parse_confidence: Math.max(Number(newPop.parse_confidence ?? 0), Number(existing.parse_confidence ?? 0)),
      parse_reason_codes: newPop.parse_reason_codes ?? existing.parse_reason_codes,
      needs_review: mergeNeedsReview(existing.needs_review, newPop.needs_review),
    };
  }

  return {
    ...newPop,
    pop_name: newPop.pop_name || existing.pop_name,
    character: newPop.character || existing.character,
    franchise: newPop.franchise || existing.franchise,
    number: newPop.number || existing.number,
    variant: newPop.variant || existing.variant,
    exclusivity,
    pop_type: newPop.pop_type || existing.pop_type,
    pop_style: newPop.pop_style || existing.pop_style,
    set_name: newPop.set_name || existing.set_name,
    set_total: existing.set_total ?? newPop.set_total,
    image_url: options.imageBlocked ? null : newPop.image_url || existing.image_url,
    vault_status: newPop.vault_status || existing.vault_status,
    release_date: newPop.release_date || existing.release_date,
    limited_edition: newPop.limited_edition || existing.limited_edition,
    limited_count: newPop.limited_count ?? existing.limited_count,
    edition_notes: newPop.edition_notes || existing.edition_notes,
    estimated_value: newPop.estimated_value ?? existing.estimated_value,
    description: newPop.description || existing.description,
    display_description: newPop.display_description || existing.display_description,
    raw_title: newPop.raw_title || existing.raw_title,
    clean_title: newPop.clean_title || existing.clean_title,
    parse_confidence: Math.max(Number(newPop.parse_confidence ?? 0), Number(existing.parse_confidence ?? 0)),
    needs_review: mergeNeedsReview(existing.needs_review, newPop.needs_review),
  };
}
